"""Bidirectional retained FUNCTION-default acceptance against pinned DuckDB.

The C++-origin case is generated by the selected reference process on every run.
Rust-origin checkpoint and WAL cases are then consumed and mutated by that same
reference. Raw revision-specific evidence belongs under ``target/``.
"""
import argparse
from dataclasses import replace
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import tempfile

from reference_version import ROOT, TARGETS, require_reference
from upstream_suite import digest
from verify_reference import Engine, command


CPP_SETUP = """
SET storage_compatibility_version='v1.5.0';
CREATE TABLE cpp_origin(
    id INTEGER,
    payload BLOB DEFAULT from_base64('AP8='),
    deferred BLOB DEFAULT from_base64('%%%')
);
INSERT INTO cpp_origin VALUES (1,from_base64('AA=='),from_base64('AQ=='));
CHECKPOINT;
"""
RUST_CHECKPOINT_SETUP = """
CREATE TABLE rust_checkpoint(
    id INTEGER,
    payload BLOB DEFAULT from_base64('AAE=')
);
INSERT INTO rust_checkpoint(id) VALUES (1);
"""
RUST_WAL_SETUP = """
CREATE TABLE rust_wal(
    id INTEGER,
    payload BLOB DEFAULT from_base64('AA==')
);
INSERT INTO rust_wal(id) VALUES (1);
"""
RUST_WAL_CHANGE = """
ALTER TABLE rust_wal ALTER COLUMN payload SET DEFAULT from_base64('AP8=');
INSERT INTO rust_wal(id) VALUES (2);
"""


def rows(engine, path, table):
    return command(
        engine,
        path,
        f"SELECT id,hex(payload) AS payload FROM {table} ORDER BY id",
        json_output=True,
        readonly=True,
    )


def expect_error(engine, path, sql):
    try:
        command(engine, path, sql)
    except RuntimeError as error:
        return str(error)
    raise AssertionError(f"expected failure from {engine.binary.name}: {sql}")


def file_evidence(path):
    wal = Path(str(path) + ".wal")
    result = {
        "checkpoint_bytes": path.stat().st_size,
        "checkpoint_sha256": digest(path),
    }
    if wal.is_file():
        result.update(wal_bytes=wal.stat().st_size, wal_sha256=digest(wal))
    return result


def cpp_origin(rust, cpp, directory):
    path = directory / "cpp-origin.duckdb"
    command(cpp, path, CPP_SETUP)
    produced = file_evidence(path)
    assert rows(rust, path, "cpp_origin") == [{"id": 1, "payload": "00"}]

    # Omitting only payload demands the valid retained FUNCTION while supplying
    # the intentionally failing sibling proves it is not evaluated eagerly.
    command(
        rust,
        path,
        "INSERT INTO cpp_origin(id,deferred) VALUES (2,from_base64('Ag=='))",
    )
    expected = [{"id": 1, "payload": "00"}, {"id": 2, "payload": "00FF"}]
    assert rows(rust, path, "cpp_origin") == expected
    rust_error = expect_error(rust, path, "INSERT INTO cpp_origin(id) VALUES (3)")
    assert rows(rust, path, "cpp_origin") == expected

    # Rust's rewrite must retain both FUNCTION trees for the independent reader.
    assert rows(cpp, path, "cpp_origin") == expected
    cpp_error = expect_error(cpp, path, "INSERT INTO cpp_origin(id) VALUES (3)")
    assert rows(cpp, path, "cpp_origin") == expected
    return {
        "producer": "pinned-cpp",
        "setup_sha256": hashlib.sha256(CPP_SETUP.encode()).hexdigest(),
        "produced": produced,
        "after_rust": file_evidence(path),
        "rows": expected,
        "rust_deferred_error": rust_error,
        "cpp_deferred_error": cpp_error,
        "passed": True,
    }


def rust_checkpoint(rust, cpp, directory):
    path = directory / "rust-checkpoint.duckdb"
    command(rust, path, RUST_CHECKPOINT_SETUP)
    produced = file_evidence(path)
    assert rows(cpp, path, "rust_checkpoint") == [{"id": 1, "payload": "0001"}]
    command(cpp, path, "INSERT INTO rust_checkpoint(id) VALUES (2); CHECKPOINT")
    expected = [
        {"id": 1, "payload": "0001"},
        {"id": 2, "payload": "0001"},
    ]
    assert rows(cpp, path, "rust_checkpoint") == expected
    assert rows(rust, path, "rust_checkpoint") == expected
    return {
        "producer": "rust-native-checkpoint",
        "setup_sha256": hashlib.sha256(RUST_CHECKPOINT_SETUP.encode()).hexdigest(),
        "produced": produced,
        "after_cpp": file_evidence(path),
        "rows": expected,
        "passed": True,
    }


def rust_wal(rust, cpp, directory):
    path = directory / "rust-wal.duckdb"
    command(rust, path, RUST_WAL_SETUP)
    logged = replace(rust, arguments=("--durability", "wal"))
    command(logged, path, RUST_WAL_CHANGE)
    produced = file_evidence(path)
    expected_recovery = [
        {"id": 1, "payload": "00"},
        {"id": 2, "payload": "00FF"},
    ]
    assert rows(cpp, path, "rust_wal") == expected_recovery
    command(cpp, path, "INSERT INTO rust_wal(id) VALUES (3); CHECKPOINT")
    expected = [*expected_recovery, {"id": 3, "payload": "00FF"}]
    assert rows(cpp, path, "rust_wal") == expected
    assert rows(rust, path, "rust_wal") == expected
    return {
        "producer": "rust-native-wal",
        "setup_sha256": hashlib.sha256(
            (RUST_WAL_SETUP + RUST_WAL_CHANGE).encode()
        ).hexdigest(),
        "produced": produced,
        "after_cpp": file_evidence(path),
        "rows": expected,
        "passed": True,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=TARGETS, default="development")
    parser.add_argument("--duckdb", type=Path)
    parser.add_argument("--rust", type=Path, default=ROOT / "target/release/duckdb-rust")
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    if args.report.exists():
        raise FileExistsError("preserve prior evidence: choose a new report path")
    reference_path, identity = require_reference(args.duckdb, target=args.target)
    rust = Engine(args.rust.resolve(strict=True), True)
    cpp = Engine(
        reference_path,
        False,
        serialize_json_rows=TARGETS[args.target].serialize_json_rows,
    )
    report = {
        "recorded_at": datetime.now(timezone.utc).isoformat(),
        "reference_identity": identity,
        "script_sha256": digest(Path(__file__)),
        "rust_binary_sha256": digest(rust.binary),
        "cases": {},
        "full_parity": False,
        "scope": (
            "Bidirectional native checkpoint/WAL acceptance for representable "
            "built-in FUNCTION defaults, including deferred failure timing."
        ),
    }
    try:
        with tempfile.TemporaryDirectory(prefix="duckdb-default-interoperability-") as temp:
            directory = Path(temp)
            report["cases"]["cpp_origin"] = cpp_origin(rust, cpp, directory)
            report["cases"]["rust_checkpoint"] = rust_checkpoint(rust, cpp, directory)
            report["cases"]["rust_wal"] = rust_wal(rust, cpp, directory)
        report["passed"] = True
    except Exception as error:
        report["passed"] = False
        report["error"] = {"type": type(error).__name__, "message": str(error)}
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps({"passed": report["passed"], "report": str(args.report)}))
    raise SystemExit(0 if report["passed"] else 1)


if __name__ == "__main__":
    main()
