"""Bidirectional retained FUNCTION-default acceptance against pinned DuckDB.

The C++-origin case is generated by the selected reference process on every run.
Rust-origin checkpoint and WAL cases are then consumed and mutated by that same
reference. Raw revision-specific evidence belongs under ``target/``.
"""

import argparse
from dataclasses import replace
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import tempfile

from reference_version import ROOT, TARGETS, require_reference
from upstream_suite import digest
from verify_reference import Engine, command


CPP_SETUP = """
SET storage_compatibility_version='v1.5.0';
CREATE TABLE cpp_origin(
    id INTEGER,
    payload BLOB DEFAULT from_base64('AP8='),
    deferred BLOB DEFAULT from_base64('%%%'),
    absent INTEGER,
    explicit_null INTEGER DEFAULT NULL
);
INSERT INTO cpp_origin(id,payload,deferred)
VALUES (1,from_base64('AA=='),from_base64('AQ=='));
CHECKPOINT;
"""
RUST_CHECKPOINT_SETUP = """
CREATE TABLE rust_checkpoint(
    id INTEGER,
    payload BLOB DEFAULT from_base64('AAE='),
    absent INTEGER,
    explicit_null INTEGER DEFAULT NULL
);
INSERT INTO rust_checkpoint(id) VALUES (1);
"""
RUST_WAL_SETUP = """
CREATE TABLE rust_wal(
    id INTEGER,
    payload BLOB DEFAULT from_base64('AA=='),
    absent INTEGER,
    explicit_null INTEGER DEFAULT NULL
);
INSERT INTO rust_wal(id) VALUES (1);
"""
RUST_WAL_CHANGE = """
ALTER TABLE rust_wal ALTER COLUMN payload SET DEFAULT from_base64('AP8=');
INSERT INTO rust_wal(id) VALUES (2);
"""
SYNTAX_COLUMNS = """
    id INTEGER,
    searched INTEGER,
    simple VARCHAR,
    null_test BOOLEAN,
    not_null_test BOOLEAN,
    range_test BOOLEAN,
    not_range_test BOOLEAN,
    in_test BOOLEAN,
    not_in_test BOOLEAN,
    like_test BOOLEAN,
    not_like_test BOOLEAN,
    interval_value INTERVAL,
    interval_unit INTERVAL
"""
SYNTAX_DEFAULTS = (
    "ALTER TABLE {table} ALTER COLUMN searched SET DEFAULT CASE WHEN 1=1 THEN 7 ELSE 0 END;"
    "ALTER TABLE {table} ALTER COLUMN simple SET DEFAULT CASE 2 WHEN 1 THEN 'one' WHEN 2 THEN 'two' ELSE 'other' END;"
    "ALTER TABLE {table} ALTER COLUMN null_test SET DEFAULT NULL IS NULL;"
    "ALTER TABLE {table} ALTER COLUMN not_null_test SET DEFAULT NULL IS NOT NULL;"
    "ALTER TABLE {table} ALTER COLUMN range_test SET DEFAULT 2 BETWEEN 1 AND 3;"
    "ALTER TABLE {table} ALTER COLUMN not_range_test SET DEFAULT 2 NOT BETWEEN 1 AND 3;"
    "ALTER TABLE {table} ALTER COLUMN in_test SET DEFAULT 2 IN (1,2,NULL);"
    "ALTER TABLE {table} ALTER COLUMN not_in_test SET DEFAULT 2 NOT IN (1,3);"
    "ALTER TABLE {table} ALTER COLUMN like_test SET DEFAULT 'duck' LIKE 'd%';"
    "ALTER TABLE {table} ALTER COLUMN not_like_test SET DEFAULT 'duck' NOT LIKE 'd%';"
    "ALTER TABLE {table} ALTER COLUMN interval_value SET DEFAULT INTERVAL '1 month 2 days 03:04:05';"
    "ALTER TABLE {table} ALTER COLUMN interval_unit SET DEFAULT INTERVAL '2.5' SECOND;"
)
RUST_SYNTAX_CHECKPOINT_SETUP = f"""
CREATE TABLE rust_syntax_checkpoint({SYNTAX_COLUMNS});
{SYNTAX_DEFAULTS.format(table="rust_syntax_checkpoint")}
INSERT INTO rust_syntax_checkpoint(id) VALUES (1);
CHECKPOINT;
"""
CPP_SYNTAX_CHECKPOINT_SETUP = f"""
SET storage_compatibility_version='v1.5.0';
CREATE TABLE cpp_syntax_checkpoint({SYNTAX_COLUMNS});
{SYNTAX_DEFAULTS.format(table="cpp_syntax_checkpoint")}
INSERT INTO cpp_syntax_checkpoint(id) VALUES (1);
CHECKPOINT;
"""
RUST_SYNTAX_WAL_SETUP = f"CREATE TABLE rust_syntax_wal({SYNTAX_COLUMNS});"
RUST_SYNTAX_WAL_CHANGE = f"""
{SYNTAX_DEFAULTS.format(table="rust_syntax_wal")}
INSERT INTO rust_syntax_wal(id) VALUES (1);
"""


def rows(engine, path, table):
    return command(
        engine,
        path,
        f"SELECT id,hex(payload) AS payload FROM {table} ORDER BY id",
        json_output=True,
        readonly=True,
    )


def null_default_metadata(engine, path, table):
    return command(
        engine,
        path,
        "SELECT column_name,column_default FROM duckdb_columns() "
        f"WHERE table_name='{table}' AND column_name IN ('absent','explicit_null') "
        "ORDER BY column_index",
        json_output=True,
        readonly=True,
    )


def syntax_rows(engine, path, table):
    return command(
        engine,
        path,
        f"SELECT * FROM {table} ORDER BY id",
        json_output=True,
        readonly=True,
    )


def expected_syntax_rows(count):
    return [
        {
            "id": row,
            "searched": 7,
            "simple": "two",
            "null_test": True,
            "not_null_test": False,
            "range_test": True,
            "not_range_test": False,
            "in_test": True,
            "not_in_test": True,
            "like_test": True,
            "not_like_test": False,
            "interval_value": "1 month 2 days 03:04:05",
            "interval_unit": "00:00:02.5",
        }
        for row in range(1, count + 1)
    ]


EXPECTED_NULL_DEFAULT_METADATA = [
    {"column_name": "absent", "column_default": None},
    {"column_name": "explicit_null", "column_default": "NULL"},
]


def expect_error(engine, path, sql):
    try:
        command(engine, path, sql)
    except RuntimeError as error:
        return str(error)
    raise AssertionError(f"expected failure from {engine.binary.name}: {sql}")


def file_evidence(path):
    wal = Path(str(path) + ".wal")
    result = {
        "checkpoint_bytes": path.stat().st_size,
        "checkpoint_sha256": digest(path),
    }
    if wal.is_file():
        result.update(wal_bytes=wal.stat().st_size, wal_sha256=digest(wal))
    return result


def cpp_origin(rust, cpp, directory):
    path = directory / "cpp-origin.duckdb"
    command(cpp, path, CPP_SETUP)
    produced = file_evidence(path)
    assert rows(rust, path, "cpp_origin") == [{"id": 1, "payload": "00"}]
    assert (
        null_default_metadata(cpp, path, "cpp_origin") == EXPECTED_NULL_DEFAULT_METADATA
    )

    # Omitting only payload demands the valid retained FUNCTION while supplying
    # the intentionally failing sibling proves it is not evaluated eagerly.
    command(
        rust,
        path,
        "INSERT INTO cpp_origin(id,deferred) VALUES (2,from_base64('Ag=='))",
    )
    expected = [{"id": 1, "payload": "00"}, {"id": 2, "payload": "00FF"}]
    assert rows(rust, path, "cpp_origin") == expected
    rust_error = expect_error(rust, path, "INSERT INTO cpp_origin(id) VALUES (3)")
    assert rows(rust, path, "cpp_origin") == expected

    # Rust's rewrite must retain both FUNCTION trees for the independent reader.
    assert rows(cpp, path, "cpp_origin") == expected
    cpp_error = expect_error(cpp, path, "INSERT INTO cpp_origin(id) VALUES (3)")
    assert rows(cpp, path, "cpp_origin") == expected
    return {
        "producer": "pinned-cpp",
        "setup_sha256": hashlib.sha256(CPP_SETUP.encode()).hexdigest(),
        "produced": produced,
        "after_rust": file_evidence(path),
        "rows": expected,
        "rust_deferred_error": rust_error,
        "cpp_deferred_error": cpp_error,
        "passed": True,
    }


def rust_checkpoint(rust, cpp, directory):
    path = directory / "rust-checkpoint.duckdb"
    command(rust, path, RUST_CHECKPOINT_SETUP)
    produced = file_evidence(path)
    assert rows(cpp, path, "rust_checkpoint") == [{"id": 1, "payload": "0001"}]
    assert (
        null_default_metadata(cpp, path, "rust_checkpoint")
        == EXPECTED_NULL_DEFAULT_METADATA
    )
    command(cpp, path, "INSERT INTO rust_checkpoint(id) VALUES (2); CHECKPOINT")
    expected = [
        {"id": 1, "payload": "0001"},
        {"id": 2, "payload": "0001"},
    ]
    assert rows(cpp, path, "rust_checkpoint") == expected
    assert (
        null_default_metadata(cpp, path, "rust_checkpoint")
        == EXPECTED_NULL_DEFAULT_METADATA
    )
    assert rows(rust, path, "rust_checkpoint") == expected
    return {
        "producer": "rust-native-checkpoint",
        "setup_sha256": hashlib.sha256(RUST_CHECKPOINT_SETUP.encode()).hexdigest(),
        "produced": produced,
        "after_cpp": file_evidence(path),
        "rows": expected,
        "passed": True,
    }


def rust_wal(rust, cpp, directory):
    path = directory / "rust-wal.duckdb"
    command(rust, path, RUST_WAL_SETUP)
    logged = replace(rust, arguments=("--durability", "wal"))
    command(logged, path, RUST_WAL_CHANGE)
    produced = file_evidence(path)
    expected_recovery = [
        {"id": 1, "payload": "00"},
        {"id": 2, "payload": "00FF"},
    ]
    assert rows(cpp, path, "rust_wal") == expected_recovery
    assert (
        null_default_metadata(cpp, path, "rust_wal") == EXPECTED_NULL_DEFAULT_METADATA
    )
    command(cpp, path, "INSERT INTO rust_wal(id) VALUES (3); CHECKPOINT")
    expected = [*expected_recovery, {"id": 3, "payload": "00FF"}]
    assert rows(cpp, path, "rust_wal") == expected
    assert (
        null_default_metadata(cpp, path, "rust_wal") == EXPECTED_NULL_DEFAULT_METADATA
    )
    assert rows(rust, path, "rust_wal") == expected
    return {
        "producer": "rust-native-wal",
        "setup_sha256": hashlib.sha256(
            (RUST_WAL_SETUP + RUST_WAL_CHANGE).encode()
        ).hexdigest(),
        "produced": produced,
        "after_cpp": file_evidence(path),
        "rows": expected,
        "passed": True,
    }


def rust_syntax_checkpoint(rust, cpp, directory):
    path = directory / "rust-syntax-checkpoint.duckdb"
    command(rust, path, RUST_SYNTAX_CHECKPOINT_SETUP)
    produced = file_evidence(path)
    assert syntax_rows(cpp, path, "rust_syntax_checkpoint") == expected_syntax_rows(1)
    command(cpp, path, "INSERT INTO rust_syntax_checkpoint(id) VALUES (2); CHECKPOINT")
    assert syntax_rows(cpp, path, "rust_syntax_checkpoint") == expected_syntax_rows(2)
    command(rust, path, "INSERT INTO rust_syntax_checkpoint(id) VALUES (3)")
    expected = expected_syntax_rows(3)
    assert syntax_rows(rust, path, "rust_syntax_checkpoint") == expected
    assert syntax_rows(cpp, path, "rust_syntax_checkpoint") == expected
    return {
        "producer": "rust-native-checkpoint",
        "setup_sha256": hashlib.sha256(
            RUST_SYNTAX_CHECKPOINT_SETUP.encode()
        ).hexdigest(),
        "produced": produced,
        "after_cpp_and_rust": file_evidence(path),
        "rows": expected,
        "passed": True,
    }


def cpp_syntax_checkpoint(rust, cpp, directory):
    path = directory / "cpp-syntax-checkpoint.duckdb"
    command(cpp, path, CPP_SYNTAX_CHECKPOINT_SETUP)
    produced = file_evidence(path)

    # The first Rust read proves the native reader accepts parsed nodes written
    # by DuckDB, before Rust has had an opportunity to republish the catalog.
    assert syntax_rows(rust, path, "cpp_syntax_checkpoint") == expected_syntax_rows(1)
    command(rust, path, "INSERT INTO cpp_syntax_checkpoint(id) VALUES (2)")
    assert syntax_rows(rust, path, "cpp_syntax_checkpoint") == expected_syntax_rows(2)

    # DuckDB must accept the defaults after Rust's catalog rewrite, then retain
    # them through its own continued write and checkpoint for a final Rust read.
    assert syntax_rows(cpp, path, "cpp_syntax_checkpoint") == expected_syntax_rows(2)
    after_rust = file_evidence(path)
    command(cpp, path, "INSERT INTO cpp_syntax_checkpoint(id) VALUES (3); CHECKPOINT")
    expected = expected_syntax_rows(3)
    assert syntax_rows(cpp, path, "cpp_syntax_checkpoint") == expected
    assert syntax_rows(rust, path, "cpp_syntax_checkpoint") == expected
    return {
        "producer": "pinned-cpp",
        "setup_sha256": hashlib.sha256(
            CPP_SYNTAX_CHECKPOINT_SETUP.encode()
        ).hexdigest(),
        "produced": produced,
        "after_rust": after_rust,
        "after_cpp": file_evidence(path),
        "rows": expected,
        "passed": True,
    }


def rust_syntax_wal(rust, cpp, directory):
    path = directory / "rust-syntax-wal.duckdb"
    command(rust, path, RUST_SYNTAX_WAL_SETUP)
    logged = replace(rust, arguments=("--durability", "wal"))
    command(logged, path, RUST_SYNTAX_WAL_CHANGE)
    produced = file_evidence(path)
    assert syntax_rows(cpp, path, "rust_syntax_wal") == expected_syntax_rows(1)
    command(cpp, path, "INSERT INTO rust_syntax_wal(id) VALUES (2); CHECKPOINT")
    assert syntax_rows(cpp, path, "rust_syntax_wal") == expected_syntax_rows(2)
    command(rust, path, "INSERT INTO rust_syntax_wal(id) VALUES (3)")
    expected = expected_syntax_rows(3)
    assert syntax_rows(rust, path, "rust_syntax_wal") == expected
    assert syntax_rows(cpp, path, "rust_syntax_wal") == expected
    return {
        "producer": "rust-native-wal",
        "setup_sha256": hashlib.sha256(
            (RUST_SYNTAX_WAL_SETUP + RUST_SYNTAX_WAL_CHANGE).encode()
        ).hexdigest(),
        "produced": produced,
        "after_cpp_and_rust": file_evidence(path),
        "rows": expected,
        "passed": True,
    }


def run_cases(cases, rust, cpp):
    results = {}
    for name, case in cases:
        try:
            with tempfile.TemporaryDirectory(
                prefix=f"duckdb-default-interoperability-{name}-"
            ) as temp:
                results[name] = case(rust, cpp, Path(temp))
        except Exception as error:
            results[name] = {
                "passed": False,
                "error": {"type": type(error).__name__, "message": str(error)},
            }
    return results


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", choices=TARGETS, default="development")
    parser.add_argument("--duckdb", type=Path)
    parser.add_argument(
        "--rust", type=Path, default=ROOT / "target/release/duckdb-rust"
    )
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    if args.report.exists():
        raise FileExistsError("preserve prior evidence: choose a new report path")
    reference_path, identity = require_reference(args.duckdb, target=args.target)
    rust = Engine(args.rust.resolve(strict=True), True)
    cpp = Engine(
        reference_path,
        False,
        serialize_json_rows=TARGETS[args.target].serialize_json_rows,
    )
    report = {
        "recorded_at": datetime.now(timezone.utc).isoformat(),
        "reference_identity": identity,
        "script_sha256": digest(Path(__file__)),
        "rust_binary_sha256": digest(rust.binary),
        "cases": {},
        "full_parity": False,
        "scope": (
            "Bidirectional native checkpoint/WAL acceptance for representable "
            "built-in FUNCTION, CASE and predicate defaults, including deferred "
            "failure timing and continued writes by both engines."
        ),
    }
    report["cases"] = run_cases(
        [
            ("cpp_origin", cpp_origin),
            ("rust_checkpoint", rust_checkpoint),
            ("rust_wal", rust_wal),
            ("cpp_syntax_checkpoint", cpp_syntax_checkpoint),
            ("rust_syntax_checkpoint", rust_syntax_checkpoint),
            ("rust_syntax_wal", rust_syntax_wal),
        ],
        rust,
        cpp,
    )
    report["passed"] = all(
        case.get("passed") is True for case in report["cases"].values()
    )
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps({"passed": report["passed"], "report": str(args.report)}))
    raise SystemExit(0 if report["passed"] else 1)


if __name__ == "__main__":
    main()
